from typing import Any, List, Set, Tuple, Dict


class EU4Date:
    def __init__(self, text: str): ...
    year: int
    month: int
    day: int

    def fancyStr(self) -> str: ...

    def isValidDate(self) -> bool: ...
    def isEU4Date(self) -> bool: ...

    @staticmethod
    def stringValid(text: str) -> bool: ...


def provinceLocation(id: int, mod: str) -> Tuple[float, float]: ...
def drawBorders(playerColors: Dict, pixels: bytes,
                width: int, height: int) -> Dict: ...


def loadProvinceMap(mod: str) -> bytes: ...
def loadMapDef(mod: str) -> Dict[int, Any]: ...
def drawMap(tagColors: Dict[str, Tuple[int, int, int]],
            provinceOwners: Dict[int, str], mod: str) -> bytes: ...


def loadWaterProvinces(mod: str) -> List[int]: ...
def generateLandAdjacency(mod: str) -> Dict[int, Set[int]]: ...
